### ISSUE TITLE
[yomu.md] フォーマットについて

### ISSUE THREAD

**Issue by shamisonn** [PMOB/study-tex#1]
ざっくり列挙します．
- [ ] 表
  - フォーマットについて
    - 自由でいいのか
    - １段目の下は２重線にするとか決めるのか
  - tableを使うのかlongtableを使うのか
    - pandocはlongtableを使うみたいです
- [ ] 画像
  - 上限サイズの策定は必要か
  - 必要ならどれくらいになりそうか
- [x] ソースコード
  - listings か verbatimか
  - verbatimは標準のモノでlistingsは標準ものを拡張したものって雰囲気ですかね
    - 参考にしました: https://www.sharelatex.com/learn/Code_listing
  - -> 長文（ソースコード）は`lstinputlisting`の利用による埋め込みを推奨し、texの中に直接書き込める程度の短いコードリストの場合はonelineスタイルの利用を推奨する。
  - -> https://github.com/PMOB/study-tex/issues/1#issuecomment-173185568

**Comment by ichi-t** [comment]
@shamison258 ソースコードについてはverbatimの方がとっかかりがいいという話だったのでverbatimに一票

**Comment by shamisonn** [comment]
verbatimはシンプルだけど機能が少ない，listingsは機能が多いけどverbatimほどシンプルでないって感じか...?

**Comment by ichi-t** [comment]
listingsのシンタックスハイライトがきになる

**Comment by matsub** [comment]
印刷・配布するものはモノクロになると思いますけど、pdf版作ることを考えるとシンタックスハイライトが効かせやすい方が良さそうですね。

listings環境はもともとリストを扱う環境として使われていて、
languageオプションでソースコードの言語を指定し、シンタックスハイライトしたり、`firstline`, `lastline`などのオプションで長文のソースリストから一部を抽出することもできます。
用途としては、別ファイルのソースコードを`lstinputlisting`コマンドで貼り付けることが多くなるように思います。

対してverbatimは言葉の通り生の文章を埋め込む環境ですので、ソースコードを記述する際の環境としてはマークアップ的にも微妙じゃないかなと思います。

ただ、一連のシェル上のコマンドを例示したりする際はソースコードリストというのも変な感じがしますし、verbatimが標準の（パッケージ不要の）環境だったら、そういった際にverbatim環境を使うとしてもいいと思います。

ソースコードリスティングに関しては、listingsの使用に一票、verbatimとの共存も検討といった意見です。

**Comment by shamisonn** [comment]
```
\documentclass[12pt]{jsbook}

\usepackage[utf8]{inputenc}
\usepackage{listings}

\begin{document}

\begin{lstlisting}[language=Python, caption=Python example]
import numpy as np

def incmatrix(genl1,genl2):
    m = len(genl1)
    n = len(genl2)
    M = None #to become the incidence matrix
    VT = np.zeros((n*m,1), int)  #dummy variable

    #compute the bitwise xor matrix
    M1 = bitxormatrix(genl1)
    M2 = np.triu(bitxormatrix(genl2),1) 

    for i in range(m-1):
        for j in range(i+1, m):
            [r,c] = np.where(M2 == M1[i,j])
            for k in range(len(r)):
                VT[(i)*n + r[k]] = 1;
                VT[(i)*n + c[k]] = 1;
                VT[(j)*n + r[k]] = 1;
                VT[(j)*n + c[k]] = 1;

                if M is None:
                    M = np.copy(VT)
                else:
                    M = np.concatenate((M, VT), 1)

                VT = np.zeros((n*m,1), int)

    return M
\end{lstlisting}
\end{document}
```

![screenshot from 2016-01-20 15-48-40](https://cloud.githubusercontent.com/assets/5053237/12442247/c3267676-bf91-11e5-8db7-07f76f16a315.png)

**Comment by shamisonn** [comment]
pythonのやーつカラー無しでハイライトやってみました．モノクロでもハイライトされてますね

（カラーに関しては，見たサイトでは独自で設定していましたが，基本的にカラーにするには独自設定という形なのかもしれません．カラーに関してはいらないかなって思う感じなので現状モノクロでいいかなって考えてます．）

**Comment by matsub** [comment]
記事を書くのとは話が逸れて大元のレイアウトの話になりますが、
lstsetプリアンブルを使うとタブ幅とかフォントとか行番号とか指定できます。

`uselist.sty`

``` tex
\usepackage{listings}
\renewcommand{\lstlistingname}{リスト}
\lstset{
  numbers=left,
  tabsize=4,
  frame=trbl,
  breaklines=true,
  basicstyle=\ttfamily,
  keywordstyle=\bf,
  commentstyle=\slshape,
  numberstyle=\ttfamily,
}
```

`list.tex`

``` tex
\documentclass{jsarticle}
\usepackage{uselist}

\begin{document}
\lstinputlisting[
  language=C,
  caption=\lstname,
  label=lst:awesomePRNG,
]{awesomePRNG.c}
\end{document}
```

<img width="780" alt="cap" src="https://cloud.githubusercontent.com/assets/7338982/12447717/d7960cac-bfb4-11e5-848b-0f8722ba4eaa.png">

特にフォントは見やすいものを選びたいです。
listingsに関してプリアンブルで指定できることは以下参照

https://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings#Settings

あまり調べてませんが、verbatimでもフォント変更はできるようです。

**Comment by shamisonn** [comment]
ちょこっとした短いコード等ではverbatimを使って，大きくなってきた場合はlistingsを使うという形がスマートですかね

**Comment by shamisonn** [comment]
個人的にtabsize指定できる感じ感動だ

**Comment by matsub** [comment]
`lstdefinestyle`プリアンブルを使ってスタイルを定義して、lstlistingのオプションでstyleを指定できるんですけど、
そこで短いコード用のスタイルを作成して

``` tex
\begin{lstlisting}[style=oneline]
> some commands..
responses
> additional commands..
\end{lstlisting}
```

としてもシンプルさは保てると思います。
この場合listingsに統一できるから判断が楽、
verbatimとlistingsでそれぞれ設定を行う必要がない
といったメリットがありますかね

**Comment by shamisonn** [comment]
なるほど確かにそれだったらlistingsだけで良いっすねぇ！
自作styを貯めとく場所作ってそこにぶっこんでやってみようか

**Comment by matsub** [comment]
長文（ソースコード）は`lstinputlisting`の利用による埋め込みを推奨し、texの中に直接書き込める程度の短いコードリストの場合はonelineスタイルの利用を推奨する。

といった体で行ってみましょう。
自作スタイルの仕様は別issueで

**Comment by shamisonn** [comment]
:+1:

**Comment by shamisonn** [comment]
This issue was moved to PMOB/hato-magazine#16

**Comment by shamisonn** [comment]
https://github-issue-mover.appspot.com/ は 神
