### ISSUE TITLE
部誌フォーマットに関して

### ISSUE THREAD

**Issue by matsub** [PMOB/study-tex#2]
プロジェクト跨ぐ話になりますけど、部紙フォーマットに関する話題はそっちのリポジトリに挙げた方がいいのでは

**Comment by shamisonn** [comment]
確かに

**Comment by shamisonn** [comment]
hato-magazineに移す感じにします

**Comment by shamisonn** [comment]
hato-magazineのwikiに書くってのはアリかな

**Comment by shamisonn** [comment]
https://github.com/PMOB/hato-magazine/wiki 移してみた

**Comment by shamisonn** [comment]
今あがってるissueに関しても移したほうがいい感でてきたので後で移します

**Comment by matsub** [comment]
:+1:

**Comment by shamisonn** [comment]
yomu.mdとyomu_extend.mdを消しとく〜〜

**Comment by shamisonn** [comment]
消したのでclose
